fix text filter + delete CursoProfesor + fix nextjs vulnerability
AlexanderArmua/sge2-nextjs pull request #13
Opened 2024-09-21 20:17 UTC by agustinarazanov

2024-09-21 22:18 UTC, AlexanderArmua requested changes
Está muy bien en general, solo agregué unas correcciones para hacer por la propia arquitectura de React

2024-09-21 22:18 UTC, AlexanderArmua commented on src/app/cursos/curso/[id]/curso-form.tsx
> +      console.log("es nuevo");
```suggestion
```

2024-09-21 22:18 UTC, AlexanderArmua commented on src/app/cursos/curso/[id]/curso-form.tsx
> +  }));
Todos estos objetos conviene declararlos afuera del componente. De otro modo React los va a estar creando cada vez que valide el ciclo de vida del componente o en otro archivo (cada interacción va a declararlos de nuevo)

2024-09-21 22:18 UTC, AlexanderArmua commented on src/app/cursos/curso/[id]/curso-form.tsx
> +    api.materia.getAll.useQuery().data?.map((item) => ({ id: item.id, label: item.nombre, data: item.anio })) ?? [];
El map es una operación barata, pero si vinieran muchos resultados lo va a ejecutar todo el tiempo con los mismos datos. 

```suggestion
  const { data } = api.materia.getAll.useQuery();

  const materias = useMemo(() => {
    return data?.map((item) => ({ id: item.id, label: item.nombre, data: item.anio })) ?? [];
  }, [data]);
```

Básicamente React valida todo el componente cada vez que ocurre un "tick" eso es cada interacción con el mismo directa indirectamente. Lo que hace que se ejecute el .map todo el tiempo. Con este código, (importando el useMemo), solo se va a ejecutar cuando cambie el data.

2024-09-21 22:18 UTC, AlexanderArmua commented on src/app/cursos/curso/[id]/curso-form.tsx
> +      .map((item) => ({ id: item.id, label: item.nombre })) ?? [];
Lo mismo que en el anterior

2024-09-21 22:18 UTC, AlexanderArmua commented on src/app/cursos/curso/[id]/curso-form.tsx
> +    }) ?? [];
Lo mismo

2024-09-21 22:18 UTC, AlexanderArmua commented on src/app/cursos/curso/[id]/curso-form.tsx
> +    console.log("modo edición");
```suggestion
```

2024-09-21 22:18 UTC, AlexanderArmua commented on src/app/cursos/curso/[id]/curso-form.tsx
> +                      .data?.map((item) => ({ id: item.id.toString(), label: item.nombre })) ?? []
Por regla de React los hooks tienen que cargar siempre, o sea no pueden renderizarse a veces si y a veces no. 

Por esto, deberías mover el hook este al principio del componente y usar una variable para este listado.

2024-09-21 22:18 UTC, AlexanderArmua commented on src/server/api/repositories/cursos/cursos.repository.ts
> +        // TODO: profesorId: input.profesorId,
```suggestion
```

2024-09-21 23:29 UTC, agustinarazanov commented on src/server/api/repositories/cursos/cursos.repository.ts
> +        // TODO: profesorId: input.profesorId,
mmm el todo lo dejo, después hay que verlo

2024-09-22 00:04 UTC, AlexanderArmua approved these changes

2024-09-22 00:04 UTC, merged